/* Generated by tools/protocol-gen. Do not edit manually. */

export type PlayerAction =
  | {
      type: "move_forward";

    }
  | {
      type: "move_back";

    }
  | {
      type: "strafe_left";

    }
  | {
      type: "strafe_right";

    }
  | {
      type: "turn_left";

    }
  | {
      type: "turn_right";

    }
  | {
      type: "cancel";

    }
  | {
      type: "enter_combat";

    }
  | {
      type: "enter_dungeon";
      dungeonType?: string;

    }
  | {
      type: "combat_action";
      action: CombatAction;

    }
  | {
      type: "flee_combat";

    }
  | {
      type: "rest";

    }
  | {
      type: "return_to_town";

    }
  | {
      type: "save_game";

    }
  | {
      type: "reset_game";

    }
  | {
      type: "swap_row";
      slot: number;

    }
  | {
      type: "tavern_recruit";
      targetId: string;

    }
  | {
      type: "mission_accept";
      targetId: string;

    }
  | {
      type: "vendor_purchase";
      targetId: string;

    }
  | {
      type: "travel";
      targetId: string;

    }
  | {
      type: "resolve_travel_encounter";
      targetId: string;

    }
  | {
      type: "set_reputation";
      targetId: string;
      value: number;

    }
  | {
      type: "complete_mission";
      targetId: string;

    }
  | {
      type: "fail_mission";
      targetId: string;

    }
  | {
      type: "abandon_mission";
      targetId: string;

    }
  | {
      type: "dialogue_choice";
      targetId: string;
      value: number;

    }
  | {
      type: "encounter_choice";
      targetId: string;

    }
  | {
      type: "branch_choose";
      targetId: string;
      branch: string;

    }
  | {
      type: "accuse_faction";
      targetId: string;

    }
  | {
      type: "transfer_to_cache";
      slot: number;
      targetId: string;
      value: number;

    }
  | {
      type: "transfer_from_cache";
      slot: number;
      targetId: string;
      value: number;

    }
  | {
      type: "downtime_action";
      targetId: string;
      downtimeAction: string;

    }
  | {
      type: "resurrect_character";
      targetId: string;

    }
  | {
      type: "wildcard_alliance";
      targetId: string;

    }
  | {
      type: "rumor_verify";
      targetId: string;
      source: string;

    };

/**
 * Shared protocol schema for C# server and TS client
 */
export interface TheReachProtocolV2 {
  envelope?: ProtocolEnvelope;
  hello?: HelloPayload;
  error?: ErrorPayload;
  heartbeatPing?: HeartbeatPingPayload;
  heartbeatPong?: HeartbeatPongPayload;
  playerAction?: PlayerAction;
  combatAction?: CombatAction;

}
export interface ProtocolEnvelope {
  v: 2;
  type: string;
  seq: number;
  ackSeq?: number;
  payload?: unknown;

}
export interface HelloPayload {
  protocolVersion: number;
  sessionId: string;

}
export interface ErrorPayload {
  code: string;
  message: string;
  recoverable: boolean;

}
export interface HeartbeatPingPayload {
  pingSeq: number;

}
export interface HeartbeatPongPayload {
  pingSeq: number;

}
export interface CombatAction {
  actorId: string;
  type: "Attack" | "Defend" | "Wait" | "UseAbility" | "UseItem" | "Flee";
  targetId?: string;
  abilityId?: string;
  itemId?: string;

}
