const { compile } = require('json-schema-to-typescript');
const fs = require('fs');
const path = require('path');

const schemaPath = path.join(__dirname, 'schema.json');
const outputPath = path.join(__dirname, '..', '..', 'src', 'client', 'src', 'types', 'protocol.gen.ts');

const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf-8'));

compile(schema, 'TheReachProtocolV2', {
  bannerComment: '/* Generated by tools/protocol-gen. Do not edit manually. */',
  declareExternallyReferenced: true,
  strictIndexSignatures: false,
})
  .then(ts => {
    // Remove index signatures added by json-schema-to-typescript
    ts = ts.replace(/^\s*\[k: string\]: unknown;\s*\n/gm, '\n');
    fs.writeFileSync(outputPath, ts);
    console.log(`Generated ${outputPath}`);
  })
  .catch(err => {
    console.error('Generation failed:', err);
    process.exit(1);
  });
